export const MENU = [
    {
        id: 'C1',
        imageKey: 'americano',
        name: 'Americano',
        description: 'Enjoy the complex flavors of espresso',
        category: 'coffee',
        price: 6.5
    },
    {
        id: 'C2',
        imageKey: 'espresso',
        name: 'Espresso',
        description: 'A thick and creamy texture, with a layer of golden foam called crema on top',
        category: 'coffee',
        price: 5.0
    },
    {
        id: 'C3',
        imageKey: 'latte',
        name: 'Latte',
        description: 'Made with espresso and steamed milk, with a thin layer of foam on top.',
        category: 'coffee',
        price: 8.5,
    },
    {
        id: 'C4',
        imageKey: 'flatwhite',
        name: 'Flat White',
        description: 'Originated in Australia and New Zealand. It is made with two shots of espresso and steamed milk',
        category: 'coffee',
        price: 8.0
    },
    {
        id: 'C5',
        imageKey: 'icedmocha',
        name: 'Iced Mocha',
        description: 'Made with chilled coffee, cold milk, ice cubes, and chocolate syrup',
        category: 'coffee',
        price: 7.5,
    },
    {
        id: 'C6',
        imageKey: 'vancappuc',
        name: 'French Vanilla Cappucino',
        description: '',
        category: 'coffee',
        price: 8.7,
    },
    {
      id: 'C7',
      imageKey: 'irish',
      name: 'Classic Irish Coffee',
      description: 'A warming drink that combines the best of coffee, whiskey, and cream',
      category: 'coffee',
      price: 9.5,
    },
    {
      id: 'C8',
      imageKey: 'vietnamese',
      name: 'Vitenamese Iced Coffee',
      description:'Experience the rich and unique flavor of Vietnam coffee culture',
      category: 'coffee',
      price: 8.5,
    },
    {
      id: 'C9',
      imageKey: 'machalatte',
      name: 'Macha Latte',
      description: 'A delicious and healthy drink that can boost your energy and mood',
      category: 'coffee',
      price: 9,
    },
    {
        id: 'M1',
        imageKey: 'chickenpanini',
        name: 'Grilled Chicken Panini',
        description: '',
        category: 'meals',
        price: 8,
      },
      {
        id: 'M2',
        imageKey: 'fishburger',
        name: 'Crispy Fish Burger',
        description: '',
        category: 'meals',
        price: 8,
      },
      {
        id: 'M3',
        imageKey: 'machabread',
        name: 'Macha Butter Sandwich',
        description: '',
        category: 'meals',
        price: 8,
      },
      {
        id: 'M4',
        imageKey: 'mozarellasandwich',
        name: 'Mozarella Sandwich',
        description: '',
        category: 'meals',
        price: 8,
      },
      {
        id: 'M5',
        imageKey: 'taco',
        name: 'Grilled Chicken Taco',
        description: '',
        category: 'meals',
        price: 8,
      }
]