export const MENU = [
    {
        id: 'C1',
        imageKey: 'americano',
        name: 'Americano',
        description: 'A great way to enjoy the complex flavors of espresso in a different way, giving you a satisfying and refreshing coffee experience.',
        category: 'coffee',
        price: 6.5
    },
    {
        id: 'C2',
        imageKey: 'espresso',
        name: 'Espresso',
        description: 'Espresso has a thick and creamy texture, with a layer of golden foam called crema on top, which adds to its aroma and taste.',
        category: 'coffee',
        price: 5.0
    },
    {
        id: 'C3',
        imageKey: 'latte',
        name: 'Latte',
        description: 'Made with espresso and steamed milk, with a thin layer of foam on top.',
        category: 'coffee',
        price: 8.5,
    },
    {
        id: 'C4',
        imageKey: 'flatwhite',
        name: 'Flat White',
        description: 'Originated in Australia and New Zealand. It is made with two shots of espresso and steamed milk, with just a small amount of foam.',
        category: 'coffee',
        price: 8.0
    },
    {
        id: 'C5',
        imageKey: 'icedmocha',
        name: 'Iced Mocha',
        description: 'Made with chilled coffee, cold milk, ice cubes, and chocolate syrup, it is a great way to treat yourself to a refreshing and decadent coffee drink. Whether you prefer it blended or on the rocks, an iced mocha will give you a satisfying and delightful coffee experience.',
        category: 'coffee',
        price: 7.5,
    },
    {
        id: 'C6',
        imageKey: 'vancappuc',
        name: 'French Vanilla Cappucino',
        description: 'If you are looking for a coffee drink that is sweet, creamy, and delicious, then you might want to try a vanilla cappuccino. A vanilla cappuccino is a coffee drink that is made with espresso, steamed milk, and vanilla flavoring. It has a smooth and frothy texture, with a rich and indulgent vanilla flavor.',
        category: 'coffee',
        price: 8.7,
    },
    {
      id: 'C7',
      imageKey: 'irish',
      name: 'Classic Irish Coffee',
      description: 'Irish coffee is a delicious and warming drink that combines the best of coffee, whiskey, and cream. It’s a perfect way to enjoy a cozy evening or celebrate a special occasion.',
      category: 'coffee',
      price: 9.5,
    },
    {
      id: 'C8',
      imageKey: 'vietnamese',
      name: 'Vitenamese Iced Coffee',
      description:'Are you looking for a coffee that is strong, sweet, and satisfying? Do you want to experience the rich and unique flavor of Vietnam coffee culture? If so, you should try Vietnamese coffee, a delicious and distinctive drink that will awaken your senses and delight your taste buds.',
      category: 'coffee',
      price: 8.5,
    },
    {
      id: 'C9',
      imageKey: 'machalatte',
      name: 'Macha Latte',
      description: 'Matcha latte is a delicious and healthy drink that can boost your energy and mood. It has a rich and complex taste that balances the bitterness of the matcha with the sweetness of the milk.',
      category: 'coffee',
      price: 9,
    },
    {
        id: 'M1',
        imageKey: 'chickenpanini',
        name: 'Grilled Chicken Panini',
        description: '',
        category: 'meals',
        price: 8,
      },
      {
        id: 'M2',
        imageKey: 'fishburger',
        name: 'Crispy Fish Burger',
        description: '',
        category: 'meals',
        price: 8,
      },
      {
        id: 'M3',
        imageKey: 'machabread',
        name: 'Macha Butter Sandwich',
        description: '',
        category: 'meals',
        price: 8,
      },
      {
        id: 'M4',
        imageKey: 'mozarellasandwich',
        name: 'Mozarella Sandwich',
        description: '',
        category: 'meals',
        price: 8,
      },
      {
        id: 'M5',
        imageKey: 'taco',
        name: 'Grilled Chicken Taco',
        description: '',
        category: 'meals',
        price: 8,
      }
]