export const MEALS = [
    {
      id: 'M1',
      imageKey: 'beef-quesadilla',
      name: 'Beef Quesadilla',
      description: '',
      category: 'meals',
      price: 12,
    },
    {
      id: 'M2',
      imageKey: 'chicken-caesar',
      name: 'Chicken Caesar',
      description: '',
      category: 'meals',
      price: 8,
    },
    {
      id: 'M3',
      imageKey: 'chicken-falafel',
      name: 'Chicken Falafel',
      description: '',
      category: 'meals',
      price: 8,
    },
    {
      id: 'M4',
      imageKey: 'cilantro-lime-shrimp',
      name: 'Cilantro-Lime Shrimp',
      description: '',
      category: 'meals',
      price: 9,
    },
    {
      id: 'M5',
      imageKey: 'grilled-salmon',
      name: 'Grilled Salmon',
      description: '',
      category: 'meals',
      price: 9,
    },
    {
      id: 'M6',
      imageKey: 'hazelnut-asian-lettuce',
      name: 'Hazelnut Asian Lettuce',
      description: '',
      category: 'meals',
      price: 8,
    },
    {
      id: 'M7',
      imageKey: 'peanutty-lettuce',
      name: 'Peanutty Lettuce',
      description: '',
      category: 'meals',
      price: 8,
    },
    {
      id: 'M8',
      imageKey: 'vegan-crunchwraps',
      name: 'Vegan Crunchwraps',
      description: '',
      category: 'meals',
      price: 8,
    }
  ]